SET LONG 100000
SET LONGCHUNKSIZE 100000
SET PAGESIZE 200
SET LINESIZE 200
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

PROMPT Generating one script with the pipelined function...

COLUMN script_line FORMAT A180

SELECT column_value AS script_line
  FROM TABLE(PKG_METADATA_SCRIPT.get_metadata_script('UTLMS_EXAMPLE_METADATA'));

