--DROP TABLE GT_METADATA_SCRIPT_FILTER_COL;

CREATE GLOBAL TEMPORARY TABLE GT_METADATA_SCRIPT_FILTER_COL
(
    STATEMENT_HANDLE    NUMBER         NOT NULL
  , PK_COL_POSITION     NUMBER         NOT NULL
  , COLUMN_NAME         VARCHAR2(30)   NOT NULL
  , DATA_TYPE           VARCHAR2(50)   NOT NULL
--  , FILTER_COLUMN_VALUE VARCHAR2(100)  
  )
ON COMMIT PRESERVE ROWS
;

--COMMENT ON COLUMN GT_METADATA_SCRIPT_FILTER_COL.FILTER_COLUMN_VALUE IS 'a NULL value indicates to generate a script for each distinct value in the column'