--DROP TABLE GT_METADATA_SCRIPT;

CREATE GLOBAL TEMPORARY TABLE GT_METADATA_SCRIPT
(
    STATEMENT_HANDLE          NUMBER         NOT NULL
  , SCHEMA_NAME               VARCHAR2(30)   NOT NULL
  , TABLE_NAME                VARCHAR2(30)   NOT NULL
  , DB_LINK                   VARCHAR2(30)
  , SCRIPT_NAME               VARCHAR2(100)
  , BREAK_BY_LEADING_PK_COLS  NUMBER(2,0)    NOT NULL
  , FILTER_PROVIDED           VARCHAR2(1)    NOT NULL
  , GENERATOR_SCRIPT          CLOB
  , DATA_SCRIPT               CLOB
  --
  , CONSTRAINT GT_METADATA_SCRIPT_CK1 CHECK ( SCHEMA_NAME = UPPER(SCHEMA_NAME) )
  , CONSTRAINT GT_METADATA_SCRIPT_CK2 CHECK ( TABLE_NAME = UPPER(TABLE_NAME) )
  , CONSTRAINT GT_METADATA_SCRIPT_CK3 CHECK ( FILTER_PROVIDED IN ('Y','N') )
  )
ON COMMIT PRESERVE ROWS
;

COMMENT ON COLUMN GT_METADATA_SCRIPT.BREAK_BY_LEADING_PK_COLS IS 'Break scripts by primary-key columns; "0" indicates not to break.';
COMMENT ON COLUMN GT_METADATA_SCRIPT.FILTER_PROVIDED IS 'Y/N. Y: A filter value was provided via add_filter_columns';
