--DROP TABLE GT_METADATA_SF_COL_VAL;

CREATE GLOBAL TEMPORARY TABLE GT_METADATA_SF_COL_VAL
(
    STATEMENT_HANDLE       NUMBER         NOT NULL
  , ID                     NUMBER         NOT NULL
  , FILTER_COLUMN_01_VALUE VARCHAR2(100)  NOT NULL
  , FILTER_COLUMN_02_VALUE VARCHAR2(100)
  , SCRIPT_NAME            VARCHAR2(100)
  , GENERATOR_SCRIPT       CLOB
  , DATA_SCRIPT            CLOB
  )
ON COMMIT PRESERVE ROWS
;

